server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/SMS
  #关闭模板引擎的缓存
  thymeleaf:
    cache: false